API Error - NotAuthenticated: Authentication credentials were not provided.
API Error - NotAuthenticated: Authentication credentials were not provided.
API Error - InvalidToken: {'detail': ErrorDetail(string='Token is invalid', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid')}
Internal Server Error: /api/auth/token/refresh/
Traceback (most recent call last):
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 141, in validate
    refresh.outstand()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework_simplejwt\tokens.py", line 222, in outstand
    return OutstandingToken.objects.get_or_create(
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'OutstandingToken' has no attribute 'objects'
"POST /api/auth/token/refresh/ HTTP/1.1" 500 114623
Internal Server Error: /api/auth/token/refresh/
Traceback (most recent call last):
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 141, in validate
    refresh.outstand()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework_simplejwt\tokens.py", line 222, in outstand
    return OutstandingToken.objects.get_or_create(
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'OutstandingToken' has no attribute 'objects'
"POST /api/auth/token/refresh/ HTTP/1.1" 500 114623
Internal Server Error: /api/auth/token/refresh/
Traceback (most recent call last):
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 141, in validate
    refresh.outstand()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\moham\Desktop\django-react-test\server\env\Lib\site-packages\rest_framework_simplejwt\tokens.py", line 222, in outstand
    return OutstandingToken.objects.get_or_create(
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'OutstandingToken' has no attribute 'objects'
"POST /api/auth/token/refresh/ HTTP/1.1" 500 114623
